Add support for OpenImageIO default_thread_pool_shutdown()
NatronGitHub/openfx-io pull request #35
Opened 2023-07-02 22:22 UTC by acolwell

Adding support for calling default_thread_pool_shutdown() on Windows. This should fix the hangs during shutdown that are happening on that platform. This function is expected to be included in the 2.5.3 release of OpenImageIO. This function has also been backported to the Natron OpenImageIO MinGW package on Windows and signalled via a
NATRON_OIIO_HAS_DEFAULT_THREAD_POOL_SHUTDOWN define.

2023-07-02 22:23 UTC, acolwell commented
This patch depends on the OpenImageIO MinGW package changes in https://github.com/NatronGitHub/Natron/pull/899

2023-07-08 01:02 UTC, devernay requested changes
Misplaced "using" statement.
See C++ Core Guideline SF.6

2023-07-08 01:02 UTC, devernay commented on OIIO/WriteOIIO.cpp
> +OIIO_NAMESPACE_USING
"using" should be after all includes

2023-07-08 01:02 UTC, devernay commented on OIIO/ReadOIIO.cpp
> +OIIO_NAMESPACE_USING
using should be after all includes

2023-07-08 01:02 UTC, devernay commented on OIIO/OIIOGlobal.cpp
> +OIIO_NAMESPACE_USING
That's where using should be. This one's ok

2023-07-10 23:50 UTC, devernay approved these changes
LGTM

2023-07-11 00:53 UTC, merged